### ISSUE TITLE
Heap allocations in family.forEach due to use of virtual EntityBag.forEach

### ISSUE THREAD

**Issue by LobbyDivinus** [Quillraven/Fleks#116]
Hi, for my current project I try to reduce memory allocations as much as possible. From my testing Fleks behaves actually pretty good in this regard with one exception: I noticed that whenever you call [family.forEach {}](https://github.com/Quillraven/Fleks/blob/625e0775d3bd6b291022259db0e0f8111c4a70ae/src/commonMain/kotlin/com/github/quillraven/fleks/family.kt#L180) a bit of memeory gets allocated which accumulates over time as this method gets usually called often (e.g. in IteratingSystems or when iterating over the entities of a family on your own). For my testing I did not add or remove any entities or components after initial setup.

Some investigation revealed that the issue is that said function calls [MutableEntityBag.forEach {}](https://github.com/Quillraven/Fleks/blob/625e0775d3bd6b291022259db0e0f8111c4a70ae/src/commonMain/kotlin/com/github/quillraven/fleks/collection/entityBag.kt#L847C22-L847C22) internally which is virtual as it implements the EntityBag interface. This is an issue here as virtual functions cannot be inlined (although, technically the call is static here) which in turn means the function parameters will have to be passed as actual lambda objects that store state on the heap.

For iteration without potential modification I came up with this solution that I can put in my own code:
```kotlin
inline fun Family.fastForEach(block: World.(Entity) -> Unit) {
    val bag = entities
    for (i in 0..<bag.size) {
        world.block(bag[i])
    }
} 
```

However, it may make sense to introduce something like this into MutableEntityBag and similar classes and use them internally instead of virtual methods.

I just noticed that you actually are allowed to use the inline keyword for non open methods although it gives you a warning. When going for this approach you would have to make sure to not call the method on the interface whenever possible: https://stackoverflow.com/questions/53188558/override-by-inline-in-kotlin

**Comment by Quillraven** [comment]
Hi,

thanks for letting me know! I initially inlined the overridden functions, but as you said, it gave a warning (or maybe even compile error?), so I removed it. Interesting that this causes a memory leak.

Would be great if you could provide a PR because at the moment my time is very limited :( But I gladly review the PR.

If you don't have time or motivation then I will fix it, but will take some time, sorry.

**Comment by LobbyDivinus** [comment]
Alright, adding inline to the functions actually does the trick. I got it down to zero allocations now. I think it's not called a memory leak when it just does unnecessary allocations that will get cleaned up by the gc eventually. But it's still something you want to avoid where possible especially on mobile.

I also added a directive to suppres the warning for that file so it should be fine. https://github.com/Quillraven/Fleks/pull/117

What I am wondering is why you are using an EntityBag interface here at all as it seems to be not implemented anywhere else. There are also methods that return EntityBag although they could return MutableEntityBag. I will come back to this if I got issues with it.

**Comment by Quillraven** [comment]
The reason for the interface was when I enhanced the family class to allow certain functionality directly like getting the first entity or filter over it, then I had to introduce an interface with limited functionality.

There was a request to add all basic Kotlin container functionality which is nowadays available in `MutableEntityBag`. The family actually uses a mutable entity bag but when a user gets that, he can potentially remove/add entities to it, which would break everything.

To avoid that, I introduced an `EntityBag` interface which does not have the mutating functionality. I guess a user could still cast the family bag to a mutable bag and modify it but at that point I don't care anymore :D I cannot protect users from everything.

Anyway, that was the reason for it - if you see a better approach then let me know! I personally don't like it that certain functions like  `isEmpty` or `first` are directly available on the family while for others you need to get the entity bag first. It is not very clean but I was never able to come up with a better strategy.

Does that answer you question?

Btw.: I saw your PR and will review it tomorrow. Thank you for your contribution!

**Comment by Quillraven** [comment]
I had another look yesterday in the evening to refresh my memory. One tricky part in the `Family` class is that it needs to store the information, which entities are part of the family and also needs to keep track if entities get added/removed.

This can happen in a "concurrent" way, meaning that while a family is iterating it can happen that entities get added/removed.

To keep my brain sane I added a "delay" mechanism back then to update entities for iteration only when necessary. I used the "dirty" flag approach here.

When accessing the entities of a family then the dirty flag is checked and the entities are updated accordingly. I remember that we wanted to make the family an ``EntityBag itself because it would be easier and more straight forward to use but because of the "mechanic" described above, we were not able to do that and went for the current approach.

**Comment by LobbyDivinus** [comment]
I see, that's not an easy design decision after all. To me it makes sense to only have limited access to the family's entities, even more limited than the current EntityBag interface as that one allows you to iterate over the entities by index which would break your protections.

However, I also really like to be able to mess around with stuff as there are always edge cases that are not covered by the API out of the box. In this example (and also for restructuring purposes) I'd suggest to add something like
```kotlin
inline fun Family.protectedAccess(block: MutableEntityBag.() -> Unit)
```
that would implement the guarding functionality. A Family.forEach could then be implemented using
```kotlin
family.protectedAccess { forEach(family.action()) }
```

If you still want to unify Family as an EntityBag I'd suggest to use inline extension methods on EntityBag to do that. They could internally explicitly differentiate between Family and non Family and use other functions of the interface for implementation.

**Comment by Quillraven** [comment]
I will have a look at this once more when the entity version PR is merged because it removed the BitArray in the family with an entity bag.

I will then fiddle around with it a little bit and see what can be done to maybe simplify it 🙂
