### ISSUE TITLE
is it possible to include entites relations like in the c++ flecs?

### ISSUE THREAD

**Issue by AnderWoche** [Quillraven/Fleks#154]
like this:
https://ajmmertens.medium.com/building-games-in-ecs-with-entity-relationships-657275ba2c6c

The other flecs: https://github.com/SanderMertens/flecs

**Comment by Quillraven** [comment]
Hi,

we had a discussion about that here: https://github.com/Quillraven/Fleks/discussions/139

In short: no, but everything is solvable by doing it in a different way.

**Comment by AnderWoche** [comment]
Maybe someone will want to build a structure like this in the future.
To be honest, I have never worked with entity relations, but I have heard that they are good for building child/parent structures.
