### ISSUE TITLE
I Need a SortedMutableEntityBag

### ISSUE THREAD

**Issue by AnderWoche** [Quillraven/Fleks#156]
Lets make MutableEntityBag **open** so i can override it and make my SortedMutableEntityBag

Important is how entities are delete: i need this way:

i want to override minusAssign

```kotlin
operator fun minusAssign(entity: Entity) {
        for (i in 0 until size) {
            if (values[i] == entity) {
                size--
                System.arraycopy(values, i + 1, values, i, size - i)
                values[size] = Entity.NONE
                return
            }
        }
    }
```

**Comment by AnderWoche** [comment]
I implemented it this way because I needed the same behavior as with an arrayList.

I didn't use a normal ArrayList because I wanted to use the EntityBag interface so that I could use the entities from the families without having to do any conversions beforehand.

I will sit down and try to make a pull request.

**Comment by AnderWoche** [comment]
I have a small question,
Why is everything in just one file?
Is it more performant?

would it be bad if I put MutableEntityBag in an extra file?

**Comment by Quillraven** [comment]
refer to the PR. If you have further questions/feedback then please let me know :)
