### ISSUE TITLE
Component family in System constructors

### ISSUE THREAD

**Issue by befora** [Quillraven/Fleks#161]
I want to cast my vote for removing component family from system constructors. I would much rather provide the family inside the class as an override function.

You may close this issue. Thanks for the library, I am enjoying the null-safety.

**Comment by Quillraven** [comment]
Where do you see the advantage of a function over a constructor arg?

**Comment by befora** [comment]
Just to separate it so I can parse it easier with my eyes. It can get messy up there with multiple components + conditions using (all,any,none).

Example:
```
class  MySystem : IteratingSystem() {
    
    override val family = family { all(MyComponent) }
    
}
```

**Comment by Quillraven** [comment]
I had that idea at the beginning but now introducing such a change will break the code for all users using 2.x version. That's why it is not gonna happen but might come in a 3.x version, if that is ever going to be released 😅
