### ISSUE TITLE
Question: Is Fleks exclusive to LibGDX, or would it work in other applications?

### ISSUE THREAD

**Issue by v79** [Quillraven/Fleks#19]
I wondered if I could use Fleks in the KorGE game engine instead, but could not get the gradle imports to work correctly. Perhaps Fleks needs LibGDX?

Many thanks!

**Comment by Quillraven** [comment]
Hi,

It is not linked to LibGDX and has actually no dependencies other than Kotlin. So, it should work.

It works for me in a normal Kotlin application on my PC at home and at the notebook at work.

What kind of error are you getting? And which IDE do you use?

**Comment by v79** [comment]
Hi,
Thanks for replying. I suspect my problem is with the complex kotlin multiplatform gradle build scripts that KorGE uses. I've added:
`implementation("io.github.quillraven.fleks:Fleks:1.0-RC1")` to `build.gradle.ktx` and I can see that it has been downloaded as an "external dependency" in IntelliJ Ultimate.

But I can't import it `import com.github.quillraven.fleks.World` highlights "com" in red with an "Unresolved reference" error. Gradle can't build the project for the same reason.

I'll try creating a plain Kotlin project (no KorGE) and see if it works there.

**Comment by v79** [comment]
Definitely a problem with KorGE; a plain Kotlin project works just fine.

**Comment by Quillraven** [comment]
I guess this might be solved with #2 but I need help for that since I am no expert for Kotlin multi platform at the moment, sorry.

If you find out how to solve it then please let me know.

The goal of Fleks in the end is to run with Kotlin multi platform and therefore it should of course work in such an environment as well.

**Comment by v79** [comment]
I'm not an expert either...

KorGE projects just have a `commonMain` src folder. In Gradle there are a couple of sourcesets defined:

```kotlin
kotlin {
    sourceSets {
        val commonMain by getting {
            kotlin.srcDir("$buildDir/generated/source/kaptKotlin/main")
            dependencies {
                implementation("io.github.quillraven.fleks:Fleks:1.0-RC1")
                implementation("com.lehaine.kiwi:kiwi:$kiwiVersion")
                implementation("org.jetbrains.kotlinx:kotlinx-serialization-json:$kotlinxSerializationVersion")
                implementation("com.soywiz.korlibs.klogger:klogger:$kloggerVersion")
            }
        }

        val jvmMain by getting {
            dependencies {
                configurations.all { // kapt has an issue with determining the correct KMM library, so we need to help it
                    if (name.contains("kapt")) {
                        attributes.attribute(
                            org.jetbrains.kotlin.gradle.plugin.KotlinPlatformType.attribute,
                            org.jetbrains.kotlin.gradle.plugin.KotlinPlatformType.jvm // pass in the JVM
                        )
                    }
                }
            }
        }
    }
}
```

It doesn't make a different if I add the Fleks dependency in `commonMain` or `jvmMain` though. I'll have to ask the KorGE developers, thought they have been very quiet recently...

Thank you for checking for me.

**Comment by Quillraven** [comment]
@v79 : where you able to add a third party dependency to KorGE now? Should we keep this issue open or can we close it for now?

**Comment by v79** [comment]
I checked with the mu;ltiplatform people on slack and it's not easy to add a JVM dependency to a kotlin multiplatform project which doesn't already have some JVM code in place. I'll keep a watch on Fleks though, would be great if it could support mutliplatform in the future. I think we should close this ticket for now.
