### ISSUE TITLE
Use Java reflection instead of Kotlin reflection

### ISSUE THREAD

**Issue by Quillraven** [Quillraven/Fleks#3]
Kotlin's reflection is super slow. E.g. calling `createInstance` of a `KClass` is ~4 times slower than calling `newInstance` of a Java `constructor`.
Also, it is an additional dependency that makes Fleks bigger than necessary which might not be relevant for Desktop but is for sure not ideal for mobile backend.

Therefore, we should remove this dependency an convert everything to "classic" reflection. Not sure if that is in conflict with #2

**Comment by Quillraven** [comment]
I had a look at that now and it seems like kotlin reflextion is only needed for the `SystemService`. It is possible to replace the `findAnnotations` and `isSubclass` calls but I have currently no idea how to replace the `primaryConstructor` and `callBy` code because with normal Java it seems like we are missing information like if parameters are optional, etc..

**Comment by Quillraven** [comment]
From my research it looks like this is impossible because Kotlin's default values are not compatible with Java reflection. The Kotlin compiler always creates a special constructor with two additional arguments: an int mask and a DefaultConstructorMaker. The second one is always null and the first one is special to define which arguments will have a default value passed to the constructor call.

It seems like it is impossible to get the information which argument has a default value via reflection and therefore I see no solution to that.

----

I then tried a different approach by using Proguard to try to reduce a fat jar. The jar without dependencies is 71kb. The fat jar is 4749 kb. The proguarded jar is 1643 kb.

This will be a problem especially on Android/Web backend where the filesize should be of course as small as possible.

Just for reference - this is what I came up with `build.gradle.kts` for the Proguard approach:

```kotlin
buildscript {
    repositories {
        mavenCentral()
    }
    dependencies {
        classpath("com.guardsquare:proguard-gradle:7.1.0")
    }
}

// non related proguard code omitted

tasks.jar {
    finalizedBy(tasks.named("proguardJar"))

    duplicatesStrategy = DuplicatesStrategy.INCLUDE

    from(files(sourceSets.main.get().output.classesDirs))
    from(configurations.runtimeClasspath.get().map { if (it.isDirectory) it else zipTree(it) })
}

tasks.create<proguard.gradle.ProGuardTask>("proguardJar") {
    dependsOn(tasks.jar)

    verbose()

    injars(tasks.jar.get())
    outjars("build/libs/${project.name}-${version}-min.jar")

    val javaHome = System.getProperty("java.home")
    if (System.getProperty("java.version").startsWith("1.")) {
        // Before Java 9, the runtime classes were packaged in a single jar file.
        libraryjars("$javaHome/lib/rt.jar")
    } else {
        // As of Java 9, the runtime classes are packaged in modular jmod files.
        libraryjars(
            mapOf(
                "jarfilter" to "!**.jar",
                "filter" to "!module-info.class"
            ),
            "$javaHome/jmods/java.base.jmod"
        )
    }

    allowaccessmodification()

    repackageclasses("")

    keep("class com.github.quillraven.fleks.** {*; }")
}
```

-----

I see now three options:
- Find a way to make it work with Java reflection. I guess this is impossible?
- Fiddle around with Proguard some more and maybe come down to a size <100 kb
- Do not support default values for systems because that way we don't need kotlin-reflect. I think it will be acceptable since most likely systems do not need default constructor parameters. 
However, I think there is then also a second issue because I couldn't find a way to find out the generic type of a `ComponentMapper` via normal Java reflection. I saw that it would be possible if mappers are normal fields of a system which could be defined as `lateinit var` but I personally prefer constructor dependencies and val if somehow possible.

Will invest some more time this week and decide for one of those options. @czyzby: maybe you have another idea for how to include kotlin-reflect but in a minified version to not explode the jar file size?

**Comment by czyzby** [comment]
> @czyzby: maybe you have another idea for how to include kotlin-reflect but in a minified version to not explode the jar file size?

Revisit compile-time annotation processing. Do not rely on reflection at runtime, use generated classes instead.

**Comment by Quillraven** [comment]
Found a way to fix `system.kt` code without using kotlin-reflect. I still use Java reflection and had a look at annotation processing / Kotlin Symbol Processing in more detail.

I think it could be a solution by e.g. automatically creating methods/constructors to allow system creations even with kotlin's default values. In my opinion it won't work with annotation processing because an `IntervalSystem` has no annotation but from what I understood KSP can parse any file and doesn't depend on annotations.

Nevertheless, for now I am happy with the current solution since I do not have a lot of time and cannot dig into the details of KSP. This is something completely new for me and for now I will postpone that.
