### ISSUE TITLE
Check needed changes and clarify open points to use Fleks directly in Korge

### ISSUE THREAD

**Issue by jobe-m** [Quillraven/Fleks#52]
As you know we have currently a copy of Fleks in Korge as Korge-fleks module. The sources in Korge-fleks are a copy of the "next" branch here.

In Korge there is a PR to remove korge-Fleks and use Fleks directly -> https://github.com/korlibs/korge-next/pull/718

I will use this space here to discuss any open points for the standalone integration/usage of Fleks with Korge.

- [x] check Fleks-ecs sample in Korge with locally released Fleks for targets JVM, js, native (linux x64, mingw x64), Android
  - [x] jvm
  - [x] js
  - [x] native (linux x86)
  - [x] native (mingw x86)
  - [x] Android (it compiles, could not test it on device yet)
- [x] check all needed build targets for Korge in a Korge game
  - [x] Fleks (common code)
  - [x] Fleks-android
  - [x] Fleks-js
  - [x] Fleks-jvm
  - [x] Fleks-linuxx64
  - [x] Fleks-mingwx64
- [x] Do final Fleks release

**Comment by Quillraven** [comment]
In my opinion we are close to something here. When we find out in #53 why the dependency cannot be used anymore in KorGE like it did before then we can release KMP-1.3 with quite some features/updates and fixes and also it is then easy to add it to any KorGE game.

As mentioned, it might be related to the SNAPSHOT version or an IntelliJ bug. I will try some more things on the weekend.

**Comment by jobe-m** [comment]
Korge has a "special" android build target which seems to be based on jvm (?) but I guess we have to support it specifically if we want to use Fleks in a Korge Android game.
Also the native target in Korge is split at least into "linux x64" and "mingw x64". So here we would also need to check how to support them.
There are also iOS and MacOS X targets but I cannot check them since I am currently unwiling to invest into that hardware ;)

**Comment by jobe-m** [comment]
I tried to use Fleks in the ecs-fleks example project in Korge and it failed because of not existing build units:
![Screenshot from 2022-06-22 14-49-37](https://user-images.githubusercontent.com/19785115/175033366-fa77b071-3818-46f9-b604-56d755e6181e.png)

So it looks that we would need to add those to Fleks if we want to use Fleks in Korge from external.

**Comment by jobe-m** [comment]
I could finally check the Fleks-ecs sample in Korge successfully while using the 1.3-KMP-SNAPSHOT local release of Fleks for at least the most common platforms as seen above.
I used as base the following branch in Korge: https://github.com/korlibs/korge/tree/feature/Update_Fleks_to_v1.3_and_adapt_ecs-fleks_sample_code
Fyi @soywiz

**Comment by Quillraven** [comment]
Not sure if this helps but maybe for android we need to check out this: https://kotlinlang.org/docs/multiplatform-publish-lib.html#publish-an-android-library

Seems like some additional gradle setup is necessary to correctly publish it?

**Comment by Quillraven** [comment]
Is there anything still pending for this issue? Or can we close it? ;)

**Comment by jobe-m** [comment]
We can close this issue here as I think we do not need any further changes in Fleks.
I will check my branch in korlibs repo and adapt it so that the Korge example for Fleks is using Fleks from Maven.
