### ISSUE TITLE
Bring DSL to JVM version

### ISSUE THREAD

**Issue by Quillraven** [Quillraven/Fleks#56]
We added a world creation DSL to the KMP version (next branch). I think it makes sense to also align that with the JVM version.

@jobe-m : I was thinking of also introducing a `world` DSL function instead of using the `World` constructor meaning that we write something like:

```kotlin
world {
  systems {
    add<Sys1>()
    add<Sys2>()
  }

  injectables {
    add("42")
    add(eventMgr)
  }
}
```

It is a minor detail but I see two benefits:
1. since everything is lower case in the current DSL it makes sense to also have the world in lowercase
2. when using Box2D we have a nameclash since Box2D also calls its "core object" World. You have to be careful when importing to choose the correct World. When we have a unique `world` DSL function and a private constructor then this nameclash is avoided and importing the wrong World, at least in that scenario, cannot happen anymore

What do you think? I can add this small adjustment to the next branch as well of course!

**Comment by jobe-m** [comment]
I fully agree. In Korge there is also Box2D integrated.
