### ISSUE TITLE
Family numEntities returns a wrong value

### ISSUE THREAD

**Issue by Quillraven** [Quillraven/Fleks#59]
I just saw that `numEntities` of a `Family` is returning a wrong value. This method is not really used inside Fleks, that's why it is not a critical bug imo but still we need to fix it.

The reason is that it returns the length of the `BitArray` which is the index of the highest set bit. This is working for our test cases with just one Entity but it is wrong in other cases.
E.g. adding just one entity with ID 7 will return a size of 8 instead of 1.

```kotlin
 @Test
fun foo() {
    val bits = BitArray()
    bits.set(7)
    println(bits.length())  // prints 8
}
```

I see two possible solutions:
- add a `size` function to `BitArray` that returns the amount of set bits
- use the family's `entitiesBag` and return the `size` of that bag

The second solution is faster but has a certain delay until it represents the correct number. This happens inside `updateActiveEntities`:
```kotlin
internal fun updateActiveEntities() {
    if (isDirty) {
        isDirty = false
        entities.toIntBag(entitiesBag)
    }
}
```

The first solution always returns the correct number but can be quite expensive in case of a lot of entities. One implementation could look like this:

```kotlin
val numBits: Int
	get() {
		var sum = 0
		for (word in bits.size - 1 downTo 0) {
			val bitsAtWord = bits[word]
			if (bitsAtWord != 0L) {
				for (bit in 63 downTo 0) {
					if ((bitsAtWord and (1L shl (bit % 64))) != 0L) {
						sum++
					}
				}
			}
		}
		return sum
	}
```

I personally prefer the first option because I think `numEntities` will not get called by users a lot per frame and it returns the expected result immediately all the time.

@jobe-m : What do you think?

**Comment by jobe-m** [comment]
I would also vote for the first solution and mark the function that it is expensive in the documentation.

**Comment by Quillraven** [comment]
part of 1.5 versions that are coming soon
