### ISSUE TITLE
Missing BitArray toString function

### ISSUE THREAD

**Issue by Quillraven** [Quillraven/Fleks#63]
In general we should improve the way to debug and analyze Fleks. Imo it is currently impossible to understand which bit of a BitArray is set which makes it hard to e.g. debug entities of a family before the bag gets updated or the component mask of an entity.

In addition, it is not comfortable to immediately see which entities have which components because of the performant and efficient way things are stored internally.

I am thinking of a toMap function for the world where the key is the entity and the value is a list of components of that entity.

Such a map can e.g. easily be converted to a JSON string for serializing but it also allows an easy overview of the current state of the world, it's entities and its components.

That should not be hard to implement with the information that the EntityService already has. It knows the active entities and the component mask of each entity which is the ComponentMapper ID of each component of the entity. The mapper can already be retrieved via the ID with the ComponentService.

**Comment by jobe-m** [comment]
Maybe name it toEntityComponentMap().
But in general I think this feature is a good addition 👍

**Comment by jobe-m** [comment]
One question just popped in my mind. Will the generated map be just a snapshot in time from the fleks entity components relation. The stuff will change quite quickly, so it will not be a map which is updated all the time automatically? I guess that would be using too much time resources. I know it is only for debugging. So we can switch it off, entirely.

**Comment by Quillraven** [comment]
It is just a snapshot. And you are right that the components and entities can quickly change. The content of the map will then be outdated but will reflect some of the changes like e.g. component data changes etc..

However, the purpose is to get a one-time snapshot and do something with it like either debugging or serializing it or whatever ;)

Shall we just call it snapshot?

**Comment by jobe-m** [comment]
I absolutely agree. Snapshot as name is a good idea. How about implementing also a restore function which takes a snapshot as input and creates the saved entities and components in a clean world. That would make it possible to implement a save state in the game and to restore it later. Use case could be "save points" in a level or (like on Android) saving the game state on background (or terminate) event and restore the game if Android killed the process while in background.

**Comment by Quillraven** [comment]
I thought about this as well and it will be a great feature but I am not sure yet how to easily solve that.

Storing the entity and its component data is rather easy imo. Can be as simple as converting the map to a JSON string.

But when it comes to loading, I don't have a good idea on how to set the data of a component properly. 
Creating the entity and adding the components is again not difficult, I think. But then setting the component data correctly inside Fleks, I have no idea 😅

In my games so far this was always a special code and I did not even need to store everything inside the world.

E.g. I only need to store the position and the type if it is a player or troll or rock or whatever. I pass this info that a "spawnEntity" function which then creates an entity with all necessary components based on the type and position.

Again, I think it will be a great and cool feature and I for sure will be able to do it for JVM only but I want to always consider KMP and there I don't know right now his to correctly restore a "state" of a specific component. Do you have an idea? Maybe it is something pretty simple and I just don't know about it 😉

**Comment by Quillraven** [comment]
Oh maybe I misunderstood you. Do you mean that the restore function already takes a map<entity,components> as input? That makes it easier to implement and leaves the serializing/deserializing up to the user. They can even then add third party libraries for that which are already available for kotlin Multiplatform as well as far as I know.

I like that more then what I described above. I guess we should then keep the entity IDs that are part of the map meaning that we need an entity create function where we can set what kind of id shall be used. Maybe we can even just manipulate the nextId of the EntityService before calling the entity create function.

I think that should work. But is that what you had in mind? 😉

**Comment by jobe-m** [comment]
> Do you mean that the restore function already takes a map<entity,components> as input?

Yes, this is what I meant.

Regarding that serialisation topic. I am thinking of storing just basic types like ints, floats, strings, arrays and simple structures in the components. No special Korge related objects like views (used for displaying sprites e.g.). Thus, saving that data is just straightforward. Then on creation of the entity e.g. a sprite, I store the needed korge objects inside the systems and access them with their entity ID.
My goal is to have the full game state inside the components. Even things like life and game score counter, health etc.
Then when restoring the entities and components the needed korge objects will be recreated inside componentlosteners and entitylisteners. 

> Maybe we can even just manipulate the nextId of the EntityService before calling the entity create function.

Yes, I guess that should work.

**Comment by jobe-m** [comment]
Sorry, I hit the wrong button ;)

**Comment by Quillraven** [comment]
@jobe-m : I implemented a `loadSnapshot` function and there is a question that popped up.

Imagine you have a snapshot like:
```
mapOf(
  Entity(1000) to listOf(Cmp1, Cmp2),
  Entity(1500) to listOf(Cmp1, Cmp3, Cmp4),
)
```

The snapshot only contains two entities. Before loading a snapshot I clear the world by calling `removeAll` because I guess you want to get the exact state of the snapshot, right?

Now imagine we have an empty world and load the snapshot from above. Shouldn`t we then just create two entities with ID 0 and 1 instead of ID 1000 and 1500? If we want to match the IDs then we also need to update the `nextId` and `recycledEntities` of the EntityService. In this example it means we need to add 1498 recycled entities and adjust the nextId to 1501. 

This is of course possible but I am not sure if want that. Maybe it is better to just work with the ids that the world is currently having and not mess around with the EntityService. The current implementation without adjusting the ids and recycled entities looks like this:

```kotlin
/**
     * Loads the given [snapshot] of the world. This will first clear any existing
     * entity of the world. After that it will load all provided entities and components.
     * This will also notify [ComponentListener] and [FamilyListener].
     *
     * @throws FleksSnapshotException if a family iteration is currently in process.
     *
     * @throws FleksMissingNoArgsComponentConstructorException if any of the components is missing
     * a no argument constructor.
     */
    fun loadSnapshot(snapshot: Map<Entity, List<Any>>) {
        if (entityService.delayRemoval) {
            throw FleksSnapshotException("Snapshots cannot be loaded while a family iteration is in process")
        }

        removeAll()
        snapshot.forEach { (_, components) ->
            with(entityService) {
                configureEntity(create { }, components)
            }
        }
    }
```

**Comment by Quillraven** [comment]
I decided to go for adjusting the EntityService accordingly because I did not like that the given ids of the map do not match the ids of the created entities. I think this is an unintuitive behavior.

Please have a look at the PR and the provided tests in the `WorldTest` file. I tried to cover all use cases but maybe I forgot something?

**Comment by jobe-m** [comment]
Sorry, for the late answer. Yes, I also like that the entity IDs are kept consistent. The reason is that I use relations between entities. E.g. a master entity contains a component with sub-entity IDs. That way the master entity can control it's slave entities. But for that the recreated world needs to have the same entity IDs as before otherwise the relations to the sub-entities would be wrong.

Great and many thanks that you found the time to already implement that feature! :)

**Comment by jobe-m** [comment]
I will have a look to the testing code later. The implementation looks ok I think.

**Comment by Quillraven** [comment]
Thank you! :)

I also added a new wiki page now for debugging information: https://github.com/Quillraven/Fleks/wiki/Debugging
