### ISSUE TITLE
[Help Request] Updating Box2D ContactListener to Fleks 2.0 Entities and Components

### ISSUE THREAD

**Issue by rubybrowncoat** [Quillraven/Fleks#70]
I have a PlayerContactListener to handle collisions in a box2d world. The physics bodies are assigned their relative fleks Entity in the body.userData property. 

The following excerpt was working using Fleks 1.6. `gameManager.entityWorld` is the Fleks world.

```kotlin
class PlayerContactListener(
    val gameManager: GameManager,
) : ContactListener {
    companion object {
        val log = logger<PlayerContactListener>()
    }

    val contacts = mutableListOf<Pair<Fixture, Fixture>>()

    val idComponentMapper = gameManager.entityWorld.mapper<IdComponent>()
    val quantityComponentMapper = gameManager.entityWorld.mapper<QuantityComponent>()

    override fun beginContact(contact: Contact?) {
        contact?.let {
            val fixtureA = it.fixtureA
            val fixtureB = it.fixtureB

            if (isPlayerContact(fixtureA, fixtureB)) {
                contacts.add(Pair(fixtureA, fixtureB))

                val physicsComponentMapper = gameManager.entityWorld.mapper<PhysicsComponent>()
                val storageComponentMapper = gameManager.entityWorld.mapper<StorageComponent>()

                val physicsComponent = physicsComponentMapper[gameManager.playerEntity]

                if (physicsComponent.targetEntity == fixtureB.body.userData || physicsComponent.targetEntity == fixtureA.body.userData) {
                    val targetEntity = (if (physicsComponent.targetEntity == fixtureA.body.userData) fixtureA.body.userData else fixtureB.body.userData) as Entity
                    val storageComponent = storageComponentMapper[targetEntity] ?: return
                    
                    // AND SO ON...
```

Now I'm trying to update the whole system to Fleks 2.0, and I've hit a snag with the storageComponent and I'm wondering what the correct approach might be.

The following in my current conversion attempt of the previous excerpt:
```kotlin
class PlayerContactListener(
    val gameManager: GameManager,
) : ContactListener {
    companion object {
        val log = logger<PlayerContactListener>()
    }

    val contacts = mutableListOf<Pair<Fixture, Fixture>>()

    override fun beginContact(contact: Contact?) {
        contact?.let {
            val fixtureA = it.fixtureA
            val fixtureB = it.fixtureB

            if (isPlayerContact(fixtureA, fixtureB)) {
                contacts.add(Pair(fixtureA, fixtureB))

                if (gameManager.playerPhysicsBodyComponent.targetEntity == fixtureB.body.userData || gameManager.playerPhysicsBodyComponent.targetEntity == fixtureA.body.userData) {
                    val targetEntity = (if (gameManager.playerPhysicsBodyComponent.targetEntity == fixtureA.body.userData) fixtureA.body.userData else fixtureB.body.userData) as Entity
                    val storageComponent = targetEntity.getOrNull(Storage) ?: return
                    
                    // AND SO ON...
```

The IDE is saying that the getOrNull method is an unresolved reference.

I thank you for any help or guidance you can provide.

- Browncoat

P.S. As a side note I pinged you on the LibGDX discord this morning, just mentioning an unexpected behaviour when creating entities in Fleks 1.6. You may not have seen it so I thought I'd mention it here as well.

P.P.S. I just noticed the discussions tab so if this is not an appropriate pace for this I can move it over there, just ask.

**Comment by Quillraven** [comment]
Hi,

creating an issue here is definitely better than discord because I am almost never online in discord :D Funny enough though, the last time I was online I also noticed that someone send me a question there but it was then already 3 weeks old or so.

So please, always create an issue/discussion here or send an e-mail to quillraven@gmail.com. That way I will try to answer as fast as I can and I get notifications on my phone.

----

If I understand your problem correctly then you are missing the `getOrNull` entity extension. This is imo correct because you are working outside a Fleks context (=world, system, family or hooks). I see two possibilities and let you choose the one you prefer:
- You most likely have a PhysicSystem that is updating your Box2D world. You can make this system a `ContactListener` then you have access to all entity extensions again.
- You pass your world instance to your `PlayerContactListener`. Then you run e.g. the entire `beginContact` function in a world context and this again will provide you with the necessary extensions:
    ```kotlin
    class PlayerContactListener(
        val gameManager: GameManager,
        private val fleksWorld: World,
    ) : ContactListener {

        // ...

    override fun beginContact(contact: Contact?) = with(fleksWorld) {
        // ...
        // now you should be able to write 'targetEntity.getOrNull(Storage) ?: return
    }
    ```

**Comment by rubybrowncoat** [comment]
I see, thanks. I have the Fleks world in my GameManager class so I should be able to use it when I need to access any entity component, but my contact listener logic was indeed quite small so I followed your suggestion and moved it inside the PhysicsSystem. I still have more things to rework to fit into Fleks 2.0 but I'm getting there.

Thanks again.

**Comment by Quillraven** [comment]
Glad I could help! If you have other questions just let me know :)
