### ISSUE TITLE
Unexpected(?) behavior with nested `entity {}` calls

### ISSUE THREAD

**Issue by rubybrowncoat** [Quillraven/Fleks#71]
This is an issue I also encountered with 1.6 but it was just before starting the update to 2.0 and I was hoping it wouldn't happen there.

```kotllin
var playerEntity: Entity?
var subEntity: Entity?

val entityWorld = world(entityCapacity = 1000) {
    // World things
}

with(entityWorld) {
    playerEntity = entity {
        it += Player()
        it += Storage().apply {
            subEntity = entity {
                it += Identifier("SUPPLIES")
                it += Quantity(210)
            }

            contents += subEntity!!
        }
        it += StageActor()
        it += TextureAnimation()
        it += PhysicsBody()
    }
}

entityWorld.snapshotOf(playerEntity!!)
entityWorld.snapshotOf(subEntity!!)
```

The internal details of PhysicsBody, TextureAnimation, StageActor and Player shouldn't be relevant. Storage has one property `contents` (a MutableList of Entity). 

The issue is that `snapshotOf(playerEntity!!)` shows it having only the Player() component, but it should have Storage, StageActor, TextureAnimation and PhysicsBody as well. While `snapshotOf(subEntity!!)` crashes with this error: 

```
Exception in thread "main" com.github.quillraven.fleks.FleksNoSuchEntityComponentException: Entity 'Entity(id=1)' has no component of type 'TextureAnimation'.
	at com.github.quillraven.fleks.ComponentsHolder.get(component.kt:131)
	at com.github.quillraven.fleks.World.snapshotOf(world.kt:448)
```

**Comment by Quillraven** [comment]
Nesting is not allowed and is at the moment intentional. Why can you not create your subentity before?

You will get a similar problem if you nest e.g. entity.configure calls with different entities.

The reason is that the EntityCreateContext gets the component mask of the newly created entity set before running your entity block code that adds the components. With your nesting you then override that with a the mask of the second entity and your remaining calls for the first entity get applied to the mask of the second entity.

We can think about changing that but I never saw someone nesting entities before. What is your reason for doing that?

**Comment by rubybrowncoat** [comment]
I'm not sure there's an intentional reason, it just felt natural to create the entities that go into a new Storage component of a new entity while creating the entity and the component themselves, since I don't need other references to them outside of that storage component's contents property (the subEntity variable above is just for example's sake). Storing them in variables and then adding them to the component just seems like an extra step, but shouldn't be an issue.

If I encounter a problem where I can't just comfortably move the entity creations out, I'll mention it. And I'll have to keep an eye out for entity.configure as well because I'd have assumed that they would work. Just a different way of thinking I guess.

Thanks.

**Comment by Quillraven** [comment]
I will try to see on the weekend if that can be changed to support nesting. I think it is feasible for both entity and configure.

I have just never seen that but if people do that I don't see a reason to not support it 😉
