### ISSUE TITLE
Better serialization support (KorGE)

### ISSUE THREAD

**Issue by Quillraven** [Quillraven/Fleks#87]
As discussed in #86 it seems to be problematic that the Fleks entity does not have the `@Serialization` annotation which makes it more complicated on user side to serialize/deserialize the snapshots of a world.

The commit of #86 is part of a new branch: `2.3-korge-serialization`

----

Things that we need to consider:
- is kotlinx-serialization the standard to serialize/deserialize stuff? Or are there other libraries out there that people might use.
  - What is LibGDX using? I know that I was able to simply convert the snapshot to a  JSON string in LibGDX and store that in a preference (MysticGarden project)
- if we add kotlinx-serialization as dependency, how much bigger does the library become? Currently it is very small because it has no dependencies at all besides standard kotlin. I'd like to keep it that way and ideally don't require the strong dependency at all.
- Can we replace the entity value class with a typealias? What downsides does that have? Does normal `Int` then also get the entity extensions? If so, I don't like that solution because it polutes standard classes. 
- Entity as an interface: what impact does that have to performance?
- Can we "generalize" the Fleks world and allow the user to override the used entity class and entity service? Per default it will use the current implementation. 
  - Maybe something like:
  ```kotlin
  val world = world {
    entityService = useDefault<UserCustomEntity>() // <-- default entity service with custom entity class
    // OR
    entityService = UserEntityService() // <-- custom service by the user with either his own entity class or the Fleks entity
  }

  // any custom entity class must provide an 'id' property to still work with the component index
  // any custom entity service must provide the current entity service functions like create/remove/...
  ```
  - not sure how easy that is and if it is even possible because entity configuration and therefore also component configuration is happening in the current entity service. Not sure how a user could still provide this functionality in his own service.
    - Maybe don't allow the complete service "replacement". Just allow the ID creation/removal and keep all the other things like component assignment, etc. in the Fleks service. So just a part of the current Fleks entity service can be customized by users.
  - However, this approach might be good for some other issues that were discussed lately where people needed their own way to create/assign IDs.

**Comment by jobe-m** [comment]
> is kotlinx-serialization the standard to serialize/deserialize stuff?

kotlinx.serialization is the standard for serializing in Kotlin multiplatform. It works for jvm, js/web and native targets. Downside is that it needs `@Serializable` annotation on each non-primitive object which should  be serialized. So that the Kotlin compiler plugin can automatically create code needed for serialization of the objects.

It is possible to write KSerializers for objects from 3rd party libs where it is not possible to add the annotation, but that requires some boilerplate code in your game serialization code. Thus, it would be good if we could either add the annotation in Fleks, reduce Entity to a primitive/interface type or decouple its creation from Fleks so that the Entity object can be annotated outside of Fleks. I guess these are the options we have.

Also it depends on what your target is. If you use Fleks only on jvm than there might be better (easier) serialization libs.

BTW I like the idea of "Just allow the ID creation/removal" outside of Fleks. I think it's worth looking into this. :)

**Comment by Frontrider** [comment]
>  is kotlinx-serialization the standard to serialize/deserialize stuff?

It is, if this library focuses on the kotlin ecosystem then it should be used.
Even if it is jvm only, it can still be desirable.

**Comment by Quillraven** [comment]
This is definitely the easy solution for now and I think it is what @jobe-m is doing.I think the library size also dies not grow by a lot (12kb or so?).

But still, I want to look into the option that users can provide their own way of creating/removing and recycling an ID as mentioned in the opening post.

Unfortunately I had no time so far but I still have it in the back of my head and won't forget it!


Unrelated but I think we should also rename the world method. I already got a few comments where people got confused by it. They tried to call it with capital W and got an error sind that it not allowed. The World constructor is internal.

I remember that IntelliJ did not suggest the constructor for me and that's why I thought it is a good enough solution but seems like others have a starting problem with it. Maybe something like newWorld or World.of or createWorld is better.

**Comment by Quillraven** [comment]
I just tried a quick&dirt implementation to allow users to override the way entities are created/removed and this is the minimum interface I could come up with:

```kotlin
interface EntityProvider {
    var nextId: Int

    fun create(): Entity

    fun prepareNextEntity(id: Int)

    fun remove(entity: Entity)

    fun isRemoved(entity: Entity): Boolean

    fun numEntities(): Int

    fun contains(entity: Entity): Boolean

    fun forEach(action: (Entity) -> Unit)

    fun reset()
}
```

So basically, someone needs to provide a way to create/remove entities and also a special way to create a specific entity the next time `create` is called (`prepareNextEntity`). This is needed for the `loadSnapshot` functions.

That's the default implementation which Fleks is currently using:

```kotlin
class DefaultEntityProvider(initialEntityCapacity: Int) : EntityProvider {
    /**
     * The id that will be given to a newly created [entity][Entity] if there are no [recycledEntities].
     */
    override var nextId = 0

    /**
     * Separate BitArray to remember if an [entity][Entity] was already removed.
     * This is faster than looking up the [recycledEntities].
     */
    @PublishedApi
    internal val removedEntities = BitArray(initialEntityCapacity)

    /**
     * The already removed [entities][Entity] which can be reused whenever a new entity is needed.
     */
    @PublishedApi
    internal val recycledEntities = ArrayDeque<Entity>()

    override fun numEntities(): Int = nextId - recycledEntities.size

    override fun create(): Entity {
        return if (recycledEntities.isEmpty()) {
            Entity(nextId++)
        } else {
            val recycled = recycledEntities.removeLast()
            removedEntities.clear(recycled.id)
            recycled
        }
    }

    override fun prepareNextEntity(id: Int) {
        recycledEntities.remove(Entity(id))
        recycledEntities.addLast(Entity(id))
    }

    override fun remove(entity: Entity) {
        removedEntities.set(entity.id)
        recycledEntities.add(entity)
    }

    override fun isRemoved(entity: Entity): Boolean = removedEntities[entity.id]

    override fun forEach(action: (Entity) -> Unit) {
        for (id in 0 until nextId) {
            val entity = Entity(id)
            if (removedEntities[entity.id]) {
                continue
            }
            action(entity)
        }
    }

    override fun reset() {
        nextId = 0
        recycledEntities.clear()
        removedEntities.clearAll()
    }

    override fun contains(entity: Entity): Boolean {
        return entity.id in 0 until nextId && !removedEntities[entity.id]
    }
}
```

I am not 100% convinced that this is the right way to go because I am not sure if a user knows all the details and information to provide a proper implementation for all methods. What do you guys think?

**Comment by jobe-m** [comment]
Sorry, I will respond a bit later since I am currently occupied with offtopic stuff ... But want to test it out for sure! :)

**Comment by jobe-m** [comment]
From a quick read through I saw that the `Entity` class is still part of Fleks. It is used as type in the interface above. Do you plan to decouple the entity type also from Fleks? At least that would be needed if we want to annotate it outside of Fleks for serialization. But I am also fine if it stays inside of Fleks and we have the annotation for serialization there. :)

**Comment by Frontrider** [comment]
> > is kotlinx-serialization the standard to serialize/deserialize stuff?
> 
> It is, if this library focuses on the kotlin ecosystem then it should be used. Even if it is jvm only, it can still be desirable.

Half offtopic remark.

One pretty big advantage of kotlinx-serialization is that it is compatible with graalvm native images (no reflections, no setup required). That is still desirable for a video game imo, as native images can drastically improve startup times (up to 10-20x). Your players want to wait as little as possible, and it gives you that with less effort.

Can also possibly result in free console support, if there is a build of graalvm for the playstation for example. (yes I know, stuff like LWJGL still needs to be ported but you get the gist of it)

**Comment by Quillraven** [comment]
> > > is kotlinx-serialization the standard to serialize/deserialize stuff?
> > 
> > 
> > It is, if this library focuses on the kotlin ecosystem then it should be used. Even if it is jvm only, it can still be desirable.
> 
> Half offtopic remark.
> 
> One pretty big advantage of kotlinx-serialization is that it is compatible with graalvm native images (no reflections, no setup required). That is still desirable for a video game imo, as native images can drastically improve startup times (up to 10-20x). Your players want to wait as little as possible, and it gives you that with less effort.
> 
> Can also possibly result in free console support, if there is a build of graalvm for the playstation for example. (yes I know, stuff like LWJGL still needs to be ported but you get the gist of it)

Thanks for the info. Kotlinx serialization was already added now in #92 .

So this part of the issue is resolved.

Now I only want to look if there is a good solution to decouple ID (=entity) creation and allow custom implementation by users.

**Comment by JonoAugustine** [comment]
Q: If `Entity` is the only serialized class and is simply an ID container, how would the state of it's components be serialized?

**Comment by jobe-m** [comment]
> Q: If `Entity` is the only serialized class and is simply an ID container, how would the state of it's components be serialized? I guess you could also phrase it as: how does world-state get serialized & replicated

The actual serialization of the components of an entity is happening outside of Fleks. It is done by serializing a "snapshot" of the Fleks ECS world. You can see how this works in the unit test of korge-fleks here:
https://github.com/korlibs/korge-fleks/blob/9c693b626aecafa74f9effa0946366b2ab3b2d7a/korge-fleks/src/commonTest/kotlin/com/soywiz/korgeFleks/components/CommonTestEnv.kt#L26

A little bit of magic is still needed around the serialization which is implemented here in korge-fleks:
https://github.com/korlibs/korge-fleks/blob/main/korge-fleks/src/commonMain/kotlin/korlibs/korge/fleks/utils/SnapshotSerializer.kt

**Comment by geist-2501** [comment]
I know that the `@Serializable` tag has been added to the `Entity` class (🥳) and that I'm late to the party, but I figured I'd mention my solution here in case kotlinx serialization gets yoinked from Fleks. I solved this without marking `Entity` as serializable by using a contextual serializer for the entity class instead, which serializes an entity as an `Int` - similar to what @jobe-m mentioned with the type alias.

```kotlin
object EntitySerializer : KSerializer<Entity> {
    override val descriptor: SerialDescriptor = PrimitiveSerialDescriptor("Entity", PrimitiveKind.INT)
    override fun serialize(encoder: Encoder, value: Entity) = encoder.encodeInt(value.id)
    override fun deserialize(decoder: Decoder): Entity = Entity(decoder.decodeInt())
}
```

Which one would add to their serializer module;

```kotlin
private val format = Json {
  serializersModule = SerializersModule {
    contextual(EntitySerializer)
  }
}
```

Which works perfectly, the only downside is that all instances of `Entity` in a serializable component need to be marked with `@Contextual`;

```kotlin
@Serializable
@SerialName("foo")
data class FooComponent(
    val otherEntities: MutableList<@Contextual Entity>
) : Component<Foo>, SerialisableComponent {
  //...
}
```

**Comment by Quillraven** [comment]
Thanks for sharing your solution as well! I try to finalize the new version of Fleks within the next two weeks. I was super busy the last weeks with moving to a new appartment with my family and my little son also demands more time than I had expected :D I don't have that much spare time anymore but I will try my best to deliver the new version soon!

I personally find it weird that it isn't so easy - at least it seems - to serialize/deserialize an entity. In the end it should be just a plain int. At least that is promised by Kotlin's value classes. I only have experience with LibGDX's serialization, which is basic JSON serialization/deserialization and there I had no issues. I am not that familiar with kotlinx-serialization and KorGE, sorry.

But I want to look into KorGE some more in the future and try to implement a simple game to see the differences to LibGDX and maybe I prefer it over LibGDX ;)

**Comment by Quillraven** [comment]
Let's keep it in because as discussed before it is the official way for kotlin multiplatform, it does not add a huge size to the bundled jar and it makes serialization life a little easier ;)

**Comment by Quillraven** [comment]
#93 is now merged into master. I will try to release version 2.4 in the upcoming weeks. This issue is resolved and we also added more flexibility with the new `EntityProvider` interface.

**Comment by Frontrider** [comment]
In my experience using an alternative would also be a clear downgrade. This is just so high quality.
