### ISSUE TITLE
New name for "world" function

### ISSUE THREAD

**Issue by Quillraven** [Quillraven/Fleks#90]
I got some mails and comments in my YouTube videos where users got confused and got errors when calling `World`. The reason is that the `World` constructor cannot be used because it is internal. Instead, users should use the `world` function.

I think the naming is not ideal because they are the same word. I also don't want to call it `createWorld`  since that clashes with LibKTX's Box2D world creation function.

Any ideas about some good namings?

My ideas:
* configureWorld
* newWorld
* cfgWorld
* worldCfg
* newEntityWorld

**Comment by jobe-m** [comment]
Good attempt. But why are you not using createWorld? Is there a technical reason that you cannot use same name like in Box2D?
configureWorld implies that the "world" is created by some other function...

**Comment by Quillraven** [comment]
I can use the same name but I always try to come up with something unique to avoid the - imho - mess of some Java stuff where you need to pick between 5+ different versions when you import a specific class.

I guess in this case it is not that crazy since it is unique if you don't use LibKTX extension and e.g. in KorGE it will be unique.

I leave it open for another 2 to 3 days. Maybe we can come up with something else. Maybe even a different name for "World"?

Otherwise, let's go for createWorld 😉

**Comment by jobe-m** [comment]
Just came into my mind:
- setUpWorld
- fleksWorld
- createECS
- ecs
- fleksECS

**Comment by Quillraven** [comment]
Let's decide between createWorld and createFleksWorld. I read a little bit and world seems to be a proper term in the context of ECS. So I think we should keep that.

I personally vote for createWorld because it is shorter 😅

**Comment by jobe-m** [comment]
I am also fine with createFleksWorld, but createWorld is shorter, yes :)

**Comment by Quillraven** [comment]
I asked AI now since nowadays we humans no longer need to think 😜

It suggested also a buildWorld naming and I asked it to choose between createWorld, buildWorld, configureWorld and just world.

It says:
`
If I had to choose one name from the options provided, I would recommend using "configureWorld" as the name for the Kotlin DSL method. 

Here's the reasoning behind this choice:
1. "buildWorld" implies that the method is responsible for constructing the world instance, but it doesn't necessarily convey the idea of customization or configuration.
2. "configureWorld" clearly indicates that the method is used to set up or configure the world instance. It aligns well with the purpose of a DSL (Domain-Specific Language), where the focus is on providing a convenient syntax for customizing an object's behavior.
3. "createWorld" is a generic term that doesn't convey the specific intention of customization or configuration. It could be used for any method that creates a world instance, which might lead to confusion in the context of a DSL.

Therefore, "configureWorld" seems like the most appropriate name for your Kotlin DSL method that creates a world instance.
`

I somehow prefer buildWorld but I understand the reasoning why configure makes more sense. However, I agree with your comment from above as well.

Anyway, the explanation from AI makes sense to me so now I change my vote to configureWorld 😅

**Comment by jobe-m** [comment]
Yes, makes absolutely sense. And also a great idea to ask a language model. Humans not relate that deeply with a topic would never come up with so much chooses and reasons ;) I would also be fine with configureWorld :)
